[theme]
font="Inter:https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"

base="light"
primaryColor="#171717"
backgroundColor="#ffffff"
secondaryBackgroundColor="#ededed"
textColor="#525252"
baseRadius="medium"
codeBackgroundColor="#f5f5f5"
codeTextColor="#ae4f4d"

redColor = "#ae4f4d"
orangeColor = "#fb8500"
yellowColor = "#e4af6c"
greenColor = "#a2a460"
blueColor = "#659bb7"
violetColor = "#db2777"
grayColor = "#a3a3a3"


[theme.sidebar]
primaryColor="#262626"
backgroundColor="#e5e5e5"
secondaryBackgroundColor="#f5f5f5"
textColor="#a3a3a3"
baseRadius="medium"
